### INDEX ###
GET http://localhost:3000/admin/users
content-type: application/json

### SHOW ###
GET http://localhost:3000/admin/users/05dd54d2-d075-4aa9-8b4f-2309e4d7c806
content-type: application/json

### CREATE ###
POST http://localhost:3000/admin/users
content-type: application/json

{  
    "user": {
        "email": "test@gmail.com",
        "username": "testinggg",
        "full_name": "test test",
        "password": "MusicManiacs21345#",
        "password_confirmation": "MusicManiacs21345#",
        "links_attributes": [
            {
                "url": "https://example.com",
                "title": "Example website",
            },
            {
                "url": "https://example.org",
                "title": "Another example website",
            }
        ]
    }
}

### UPDATE ###
PUT http://localhost:3000/admin/users/227267a3-4870-46ed-912f-6f0ad56014e3
content-type: application/json

{  
    "user": {
        "email": "emailchange@gmail.com",
        "links_attributes": [
            {
                "id": "uuid de algun link",
                "url": "https://example.com",
                "title": "Update Example website",
            },
            {
                "id": "uuid de algun link",
                "url": "https://example.org",
                "title": "Another example website",
                "_destroy": true
            }
        ]
    }
}

### DESTROY ###
DELETE http://localhost:3000/admin/users/05dd54d2-d075-4aa9-8b4f-2309e4d7c806
content-type: application/json