### INDEX ###
GET http://localhost:3000/admin/events?q[name_cont]=Pasado&page=10&per_page=1
content-type: application/json

### SHOW ###
GET http://localhost:3000/admin/events/68a2ea25-b8b2-4e73-ac0c-51bc34f73caa
content-type: application/json

### CREATE ###
POST http://localhost:3000/admin/events
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="event"

{
    "name":"Digweed, Metropolitano 2023",
    "datetime": "2023-09-13 19:30:10",
    "artist_id": "feb601ed-3161-46e9-90de-386183272428",
    "producer_id": "f5aeea44-b41b-44f2-aa5c-2fc7356966be",
    "venue_id": "35f823b9-70a0-4cd2-9e51-b926ad532976",
    "description": "description"
}
------WebKitFormBoundary7MA4YWxkTrZu0gW

Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/jpg

< lib/endpoints/assets/ArtistCover.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### UPDATE ###
PUT http://localhost:3000/admin/events/3e47fcce-194c-4f62-88b4-0dd083c6c88c
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="event"

{
    "name":"Digweed Update"
}------WebKitFormBoundary7MA4YWxkTrZu0gW

Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/jpg

< /lib/endpoints/assets/ArtistCover.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### DESTROY ###
DELETE http://localhost:3000/admin/events/3e47fcce-194c-4f62-88b4-0dd083c6c88c
content-type: application/json
