###### SHOW ######
GET http://localhost:3000/admin/followers/05dd54d2-d075-4aa9-8b4f-2309e4d7c806
content-type: application/json

###### FOLLOW ######

### VENUE ###
POST http://localhost:3000/admin/followers/follow_venue
content-type: application/json

{
  "id": "a9eac9f5-6127-4a91-84c5-b10d51a07e56"
}

### PRODUCER ###
POST http://localhost:3000/admin/followers/follow_producer
content-type: application/json

{
  "id": "a9eac9f5-6127-4a91-84c5-b10d51a07e56"
}

### ARTIST ###
POST http://localhost:3000/admin/followers/follow_artist
content-type: application/json

{
  "id": "a9eac9f5-6127-4a91-84c5-b10d51a07e56"
}

###### DESTROY ######

### VENUE ###
DELETE http://localhost:3000/admin/followers/follow_venue/a9eac9f5-6127-4a91-84c5-b10d51a07e56
content-type: application/json

### PRODUCER ###
DELETE http://localhost:3000/admin/followers/follow_producer/a9eac9f5-6127-4a91-84c5-b10d51a07e56
content-type: application/json

### ARTIST ###
DELETE http://localhost:3000/admin/followers/follow_artist/a9eac9f5-6127-4a91-84c5-b10d51a07e56
content-type: application/json
