###### SHOW ######
GET http://localhost:3000/followers/05dd54d2-d075-4aa9-8b4f-2309e4d7c806
content-type: application/json

###### FOLLOW ######

### VENUE ###
POST http://localhost:3000/followers/follow_venue
content-type: application/json

{
  "venue": {
    "id": "c90baaba-d19a-4e53-a152-08f10554af00"
  }
}

### PRODUCER ###
POST http://localhost:3000/followers/follow_producer
content-type: application/json

{
  "producer": {
    "id":"be724a65-9c33-4ea6-bd1e-fe23aa0f1349"
  }
}

### ARTIST ###
POST http://localhost:3000/followers/follow_artist
content-type: application/json

{
  "artist": {
        "id":"3ea621e1-1907-4e20-9c93-4ce72644e13f"
  }
}

###### UNFOLLOW ######

### VENUE ###
DELETE http://localhost:3000/followers/follow_venue/be724a65-9c33-4ea6-bd1e-fe23aa0f1349
content-type: application/json

### PRODUCER ###
DELETE http://localhost:3000/followers/follow_producer/a9eac9f5-6127-4a91-84c5-b10d51a07e56
content-type: application/json

### ARTIST ###
DELETE http://localhost:3000/followers/follow_artist/3ea621e1-1907-4e20-9c93-4ce72644e13f
content-type: application/json
