### INDEX ###
GET http://localhost:3000/admin/locations
content-type: application/json

### CREATE ###
POST http://localhost:3000/admin/locations
content-type: application/json

{
  "location": {
    "zip_code": "12345",
    "street": "Italia",
    "department": "Guaymallen",
    "locality": "Capilla del Rosario",
    "latitude": "40.7128",
    "longitude": "-74.0060",
    "number": 4,
    "country": "United States",
    "province": "New York"
  }
}

### SHOW ###
GET http://localhost:3000/admin/locations?id=a07a0143-0b13-4849-9a6e-a53cf4be2608
content-type: application/json


### UPDATE ###
PUT http://localhost:3000/admin/venues/a07a0143-0b13-4849-9a6e-a53cf4be2608
content-type: application/json

{
    "location": {
        "street": "calle siempre alegre",
        "id": "804545e1-7deb-4187-bca2-78a74b23dc93",
        "zip_code": "12345",
        "department": "Guaymallen",
        "locality": "Capilla del Rosario",
        "latitude": "40.7128",
        "longitude": "-74.0060",
        "number": 5,
        "country": "ARGENTINA",
        "province": "MENDOZA"
    }
}

### DESTROY ###
DELETE http://localhost:3000/admin/venues/a07a0143-0b13-4849-9a6e-a53cf4be2608
content-type: application/json