### INDEX ###
GET http://localhost:3000/admin/producers?q[name_cont]=Pasado&page=10&per_page=1
content-type: application/json

### SHOW ###
GET http://localhost:3000/admin/producers/90efa702-f1bd-46f2-aa15-e4fcb6def60e
content-type: application/json

### CREATE ###
POST http://localhost:3000/admin/producers
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="producer"

{"name":"Productora Nuevos","nationality":"generos","description":"aaa","genre_ids":["4b4df81d-9a0d-4bb2-a928-e21b7270daa9"],"links_attributes":[{"title":"aaaaaa","url":"aaaaaa"},{"title":"vvvv","url":"vvvv"}]}
------WebKitFormBoundary7MA4YWxkTrZu0gW

Content-Disposition: form-data; name="image"; filename="losinso.png"
Content-Type: image/jpg

< lib/endpoints/assets/losinso.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### UPDATE ###
PUT http://localhost:3000/admin/producers/64ba21a4-3ead-4ff6-b0ff-029f30f09aa2
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="producer"

{"name":"Productora Nuevos","nationality":"generos","description":"aaaa","genre_ids":["4b4df81d-9a0d-4bb2-a928-e21b7270daa9"],"links_attributes":[{"id":"46df7ea6-7118-437c-ae87-1bc1be5ab508","title":"aaaaaa","url":"aaaaaa"},{"id":"b0ed9b16-dcd7-48dd-92fc-56be95b16d78","title":"vvvv","url":"vvvv"}]}
------WebKitFormBoundary7MA4YWxkTrZu0gW

Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/jpg

< /lib/endpoints/assets/ArtistCover.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### DESTROY ###
DELETE http://localhost:3000/admin/producers/2a77c024-44fc-46c0-8daa-7a42b7deb3a7
content-type: application/json

### TYPEAHEAD ###
GET http://localhost:3000/admin/producers/search_typeahead?q[name_cont]=Productora
content-type: application/json