### INDEX ###
GET http://localhost:3000/admin/users?q[name_or_username_or_email_matches]=test&q[search_by_state]=active&page=10&per_page=1
content-type: application/json

### SHOW ###
GET http://localhost:3000/admin/users/05dd54d2-d075-4aa9-8b4f-2309e4d7c806
content-type: application/json

### CREATE ###
POST http://localhost:3000/admin/users
content-type: application/json

{  
    "user": {
        "email": "test@gmail.com",
        "username": "testinggg",
        "full_name": "test test",
        "password": "MusicManiacs21345#",
        "password_confirmation": "MusicManiacs21345#",
        "links_attributes": [
            {
                "url": "https://example.com",
                "title": "Example website"
            },
            {
                "url": "https://example.org",
                "title": "Another example website"
            }
        ],
        "role_id": "5153db24-3c0a-401b-9449-a78959e3425a"
    }
}

### UPDATE ###
PUT http://localhost:3000/admin/users/227267a3-4870-46ed-912f-6f0ad56014e3
content-type: application/json

{  
    "user": {
        "email": "emailchange@gmail.com",
        "links_attributes": [
            {
                "id": "uuid de algun link",
                "url": "https://example.com",
                "title": "Update Example website"
            },
            {
                "id": "uuid",
                "_destroy": true
            },
            {
                "url": "https://example.org",
                "title": "nuevo link"
            }
        ]
    }
}

### DESTROY ###
DELETE http://localhost:3000/admin/users/05dd54d2-d075-4aa9-8b4f-2309e4d7c806
content-type: application/json


### RESTORE ###
PUT http://localhost:3000/admin/users/e6af483a-85dd-48c9-b526-2f1c56f497a9/restore
content-type: application/json