### INDEX ###
GET http://localhost:3000/admin/venues?page=1&per_page=1
content-type: application/json


### CREATE ###
POST http://localhost:3000/admin/venues
content-type: application/json

{
  "venue": {
    "name": "Nombre del lugar",
    "description": "Descripción del lugar",
    "links_attributes": [
      {
        "url": "https://example.com",
        "title": "Example website"
      },
      {
        "url": "https://example.org",
        "title": "Another example website"
      }
    ],
    "location_attributes": {
      "zip_code": "12345",
      "street": "Calle Principal",
      "department": "Departamento",
      "locality": "Localidad",
      "latitude": "12.345",
      "longitude": "-67.890",
      "number": "123",
      "country": "País",
      "province": "Provincia"
    }
  }
}

### SHOW ###
GET http://localhost:3000/admin/venues?id=503f2f07-be66-49da-9f23-ea57cce6b620
content-type: application/json

### SHOW ###
GET http://localhost:3000/admin/venues?venue_name=Primer Lugar
content-type: application/json


### UPDATE ###
PUT http://localhost:3000/admin/venues/d1c8f115-f908-48f8-9389-f8bc46024b32
content-type: application/json

{
    "venue": {
        "id": "d1c8f115-f908-48f8-9389-f8bc46024b32",
        "description": "Descripcion del lugar de eventos",
        "name": "Primer Lugar",
        "links_attributes": [
      {
        "url": "https://example.com",
        "title": "Example website"
      },
      {
                "id": "uuid",
                "_destroy": true
            },
      {
        "url": "https://example.org",
        "title": "Another example website"
      }
    ]
    },
    "location_attributes":
        {
          "zip_code": "12345",
          "street": "Italia",
          "department": "Guaymallen",
          "locality": "Capilla del Rosario",
          "latitude": "40.7128",
          "longitude": "-74.0060",
          "number": 4,
          "country": "United States",
          "province": "New York"
    }
}

### DESTROY ###
DELETE http://localhost:3000/admin/venues/c474c64f-261a-4337-a28f-10ea415a6807
content-type: application/json