### INDEX ###
GET http://localhost:3000/admin/venues
content-type: application/json


{
    "venue": {
        "id": "c474c64f-261a-4337-a28f-10ea415a6807",
        "description": "Descripcion del lugar de eventos",
        "venue_name": "Primer Lugar",
        "linkeable_id": null,
        "linkeable_type": null,
        "created_at": "2023-08-25T13:55:34.697Z",
        "updated_at": "2023-08-25T13:55:34.697Z",
        "links_attributes": [
          {
            "url": "https://example.com",
            "title": "Example website"
          },
          {
            "url": "https://example.org",
            "title": "Another example website"
          }
        ]
    }
}

### CREATE ### ESTO NO ANDA
POST http://localhost:3000/admin/venues
content-type: application/json

{
  "venue": {
    "venue_name": "Nombre del lugar",
    "description": "Descripción del lugar",
    "links_attributes": [
      {
        "url": "https://example.com",
        "title": "Example website"
      },
      {
        "url": "https://example.org",
        "title": "Another example website"
      }
    ],
    "location_attributes": {
      "zip_code": "12345",
      "street": "Calle Principal",
      "department": "Departamento",
      "locality": "Localidad",
      "latitude": "12.345",
      "longitude": "-67.890",
      "number": "123",
      "country": "País",
      "province": "Provincia"
    }
  }
}

### SHOW ###
GET http://localhost:3000/admin/venues?id=c474c64f-261a-4337-a28f-10ea415a6807
content-type: application/json

### SHOW ###
GET http://localhost:3000/admin/venues?venue_name=Primer Lugar
content-type: application/json


### UPDATE ###
PUT http://localhost:3000/admin/venues/c474c64f-261a-4337-a28f-10ea415a6807
content-type: application/json

{
    "venue": {
        "id": "c474c64f-261a-4337-a28f-10ea415a6807",
        "description": "Descripcion del lugar de eventos",
        "venue_name": "Primer Lugar",
        "linkeable_id": null,
        "linkeable_type": null,
        "created_at": "2023-08-25T13:55:34.697Z",
        "updated_at": "2023-08-25T13:55:34.697Z",
        "links_attributes": [
      {
        "url": "https://example.com",
        "title": "Example website"
      },
      {
                "id": "uuid",
                "_destroy": true
            },
      {
        "url": "https://example.org",
        "title": "Another example website"
      }
    ]
    },
    "location_attributes":
        {
          "id": "e692f532-c482-4b19-88e0-082d7716d250",
          "zip_code": "12345",
          "street": "Italia",
          "department": "Guaymallen",
          "locality": "Capilla del Rosario",
          "latitude": "40.7128",
          "longitude": "-74.0060",
          "number": 4,
          "country": "United States",
          "province": "New York",
          "venue_id": null,
          "created_at": "2023-08-27T19:04:22.331Z",
          "updated_at": "2023-08-27T19:04:22.331Z"
    }
}

### DESTROY ###
DELETE http://localhost:3000/admin/venues/c474c64f-261a-4337-a28f-10ea415a6807
content-type: application/json