### USER_INFO ###
GET http://localhost:3000/users/user_info
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZWRlZmJiMS01OTUwLTQ5NWYtODQ5MS02NWQzZmUzZmY1NDgiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTUzMTI5OTcsImV4cCI6MTY5ODMzNjk5NywianRpIjoiYzBmNzA0MmItYzc1OC00YzY1LWJmZTctMTk3OTRjNDU1YzZjIn0.NhBi3ij_JjsPXCYGYwHfttCISjfNqy2rokO2JaOhZNw

### Editar Perfil ###
PUT http://localhost:3000/users/current
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZWRlZmJiMS01OTUwLTQ5NWYtODQ5MS02NWQzZmUzZmY1NDgiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTUzMTI5OTcsImV4cCI6MTY5ODMzNjk5NywianRpIjoiYzBmNzA0MmItYzc1OC00YzY1LWJmZTctMTk3OTRjNDU1YzZjIn0.NhBi3ij_JjsPXCYGYwHfttCISjfNqy2rokO2JaOhZNw
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user"

{
        "email": "emailchange@gmail.com",
        "full_name": "New full_name",
        "username": " New unique username",
        "links_attributes": [
            {
                "url": "https://example.com",
                "title": "Update Example website"
            },
            {
                "url": "https://example.org",
                "title": "nuevo link"
            },
            {
                "id": "uuid_link",
                "_destroy": true
            }
        ],
        "images_attributes": [
            {
                "id": "uuid_image",
                "_destroy": true
            },
            {
                "id": "uuid_image",
                "_destroy": true
            }
        ]
}
------WebKitFormBoundary7MA4YWxkTrZu0gW

Content-Disposition: form-data; name="images[]"; filename="Perfil.jpg"
Content-Type: image/jpeg

/lib/endpoints/assets/ArtistCover.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images[]"; filename="Portada.jpg"
Content-Type: image/jpeg

/lib/endpoints/assets/losinso.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Eliminar Usuario ###
DELETE http://localhost:3000/users/current
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZWRlZmJiMS01OTUwLTQ5NWYtODQ5MS02NWQzZmUzZmY1NDgiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTUzMTI5OTcsImV4cCI6MTY5ODMzNjk5NywianRpIjoiYzBmNzA0MmItYzc1OC00YzY1LWJmZTctMTk3OTRjNDU1YzZjIn0.NhBi3ij_JjsPXCYGYwHfttCISjfNqy2rokO2JaOhZNw

### Cambiar Contraseña ###
PUT http://localhost:3000/users/current/change_password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZWRlZmJiMS01OTUwLTQ5NWYtODQ5MS02NWQzZmUzZmY1NDgiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTUzOTMwMDEsImV4cCI6MTY5ODQxNzAwMSwianRpIjoiYjhhOWFlZTgtZTJlMC00MmE0LThkYjctMjQyNzEyZTc4ZTI4In0.vUQIYTVlu1tPt9Av-iIlB0pnNjxAoJyL0p8nYXu7VAg

{ "user":
    { "password": "MusicManiacs21345#",
      "password_confirmation": "MusicManiacs21345#"
    }
}

### Obtener Seguidos por tipo ###
GET http://localhost:3000/users/current/followed?q[followable_type_cont]=Artist&page=1&per_page=5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZWRlZmJiMS01OTUwLTQ5NWYtODQ5MS02NWQzZmUzZmY1NDgiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTUzOTMwMDEsImV4cCI6MTY5ODQxNzAwMSwianRpIjoiYjhhOWFlZTgtZTJlMC00MmE0LThkYjctMjQyNzEyZTc4ZTI4In0.vUQIYTVlu1tPt9Av-iIlB0pnNjxAoJyL0p8nYXu7VAg

### Obtener Seguidos por nombre ###
GET http://localhost:3000/users/current/followed?q[followable_name_cont]="Usted Señalemelo"&page=1&per_page=5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZWRlZmJiMS01OTUwLTQ5NWYtODQ5MS02NWQzZmUzZmY1NDgiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTUzOTMwMDEsImV4cCI6MTY5ODQxNzAwMSwianRpIjoiYjhhOWFlZTgtZTJlMC00MmE0LThkYjctMjQyNzEyZTc4ZTI4In0.vUQIYTVlu1tPt9Av-iIlB0pnNjxAoJyL0p8nYXu7VAg