### User Registration ###
POST http://localhost:3000/users
content-type: application/json

{  
    "user": {
        "email": "test@gmail.com",
        "username": "test",
        "full_name": "test test",
        "password": "MusicManiacs21345#",
        "password_confirmation": "MusicManiacs21345#"
    }
}

### User Login ###
POST http://localhost:3000/users/sign_in
Content-Type: application/json

{
  "user": {
    "login": "test@gmail.com",
    "password": "MusicManiacs21345#"
  }
}

### Current User info ###
GET http://localhost:3000/users/user_info
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIaOiI5ZDlmYmQ3OC04ZTZjLTRiZmMtODY2YS00OTk1MjQwNTM3MGUiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTIxMjY2ODMsImV4cCI6MTY5MjEyNjk4MywianRpIjoiOTUxOGFhZmUtNWRkZC00YzcyLTk1ODYtODhiYzQzNGM0NjlhIn0.d5D9NZlbDWk9jvHIokt-tusKuDLa9usWHElVTLYC4Co
Content-Type: application/json

### User Logout ###
DELETE http://localhost:3000/users/sign_out
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5ZDlmYmQ3OC04ZTZjLTRiZmMtODY2YS00OTk1MjQwNTM3MGUiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTIxMjY0ODcsImV4cCI6MTY5MjEyNjc4NywianRpIjoiYzRkZDM3OTAtMjQyYS00MWFhLWI1NTYtZWVlMDJiNjMyOGI3In0.o6-ysuclXRYqj9v8_seZHdi0FVpdMHLzRa9DRumB40g


### Recover password email ###
POST http://localhost:3000/users/password
Content-Type: application/json

{
  "user": {
    "email": "test@gmail.com"
  }
}

### Recover password ###
PATCH http://localhost:3000/users/password
Content-Type: application/json

{
  "user": {
    "reset_password_token": "PDzxxbWcvdXuowFF2kTP",
    "password": "MusicManiacs21345",
    "password_confirmation": "MusicManiacs21345#"
  }
}