### FOLLOW ###
POST http://localhost:3000/artists/f68d289b-a5df-4296-8859-a14a51690460/follow
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOGNhMjdjOS0xN2IwLTQ3ZDItOWUyYS1kZjY4M2YzOWQyM2EiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTQwMzc2MTcsImV4cCI6MTY5NzA2MTYxNywianRpIjoiMjAxMmQ1ZWYtMDQ1My00MDEzLThmYmQtZTllODY3NDVlNzk1In0.7GKbaHZuEu7Och5uzjeuJwET6TH2zUtNjSZMm6HtQ1E
content-type: application/json

### UNFOLLOW ###
POST http://localhost:3000/artists/f68d289b-a5df-4296-8859-a14a51690460/unfollow
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjOGNhMjdjOS0xN2IwLTQ3ZDItOWUyYS1kZjY4M2YzOWQyM2EiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTQwMzc2MTcsImV4cCI6MTY5NzA2MTYxNywianRpIjoiMjAxMmQ1ZWYtMDQ1My00MDEzLThmYmQtZTllODY3NDVlNzk1In0.7GKbaHZuEu7Och5uzjeuJwET6TH2zUtNjSZMm6HtQ1E
content-type: application/json
