### index_backup ###
GET /backup HTTP/1.1
Host: localhost:3000

### restore_backup ###
POST /backup HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Content-Length: 37

{
      "id": "2023.10.05.14.31.31"
}

### delete_backup ###
POST /backup/delete HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Content-Length: 37

{
      "id": "2023.10.06.13.56.11"
}