### SHOW ###
GET http://localhost:3000/events/f01f6f53-a2d7-4134-9a8f-5e3f6943b6fd
content-type: application/json

### SEARCH ###
GET http://localhost:3000/events/search
content-type: application/json

### CREATE ###
POST http://localhost:3000/events
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="event"

{
    "name":"Digweed, Metropolitano 2023",
    "datetime": "2023-09-05 19:30:10",
    "artist_id": "c91da1e7-16a2-43ee-8d1d-849fee5f4064",
    "producer_id": "55d5f4e2-c769-456e-88f9-bbd54f07da0b",
    "venue_id": "ba1a582b-a59b-41b1-9803-79f261658dd9",
    "description": "description"
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="LOSINSO.jpg"
Content-Type: image/jpeg

/lib/endpoints/assets/ArtistCover.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="video"; filename="RetratoFamiliar.mp4"
Content-Type: video/mp4

lib/endpoints/assets/RetratoFamiliar.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### UPDATE ###
PUT http://localhost:3000/events/1e0b6c21-da00-4f1a-8e54-71e0607d54ba
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="event"

{
    "name":"Digweed, Modified",
    "videos_attributes":{
        "id":"uuid",
        "_destroy": true
    }
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="LOSINSO.jpg"
Content-Type: image/jpeg

/lib/endpoints/assets/ArtistCover.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="video"; filename="RetratoFamiliar.mp4"
Content-Type: video/mp4

lib/endpoints/assets/RetratoFamiliar.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### FOLLOW ###
POST http://localhost:3000/events/f01f6f53-a2d7-4134-9a8f-5e3f6943b6fd/follow
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2ODA2NDQ1OS1jMzlmLTQ4YTUtOTUyNy01MzkyYzNmZTRlNWUiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTUxNjQ3MzUsImV4cCI6MTY5ODE4ODczNSwianRpIjoiMGJjNDg4M2UtNmQxNC00ZmUxLWFhOTQtODU1NzExMWYwNTI5In0.O3Fu1vQTS7TqFpgDl3UetUo7KydgScrt9WtxVc7graM
content-type: application/json

### UNFOLLOW ###
POST http://localhost:3000/events/f01f6f53-a2d7-4134-9a8f-5e3f6943b6fd/unfollow
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2ODA2NDQ1OS1jMzlmLTQ4YTUtOTUyNy01MzkyYzNmZTRlNWUiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTUxNjQ3MzUsImV4cCI6MTY5ODE4ODczNSwianRpIjoiMGJjNDg4M2UtNmQxNC00ZmUxLWFhOTQtODU1NzExMWYwNTI5In0.O3Fu1vQTS7TqFpgDl3UetUo7KydgScrt9WtxVc7graM
content-type: application/json

### LIKE ###
POST http://localhost:3000/events/01bc2211-ef15-4ceb-8511-ed82c68d4d0f/like
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4YmQ3YmM2MC1jMGMyLTRiMTgtOTRiZS02ZjViMjk4NmRjNWEiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTQ2MjY2MTgsImV4cCI6MTY5NzY1MDYxOCwianRpIjoiMTQ2OTQwZDUtYjI1Ni00NDhlLTg0M2ItNGY4OTMyN2M2NTEzIn0.-XYdiQpanu4yNSmYsZ2kTbYxnkRYlfrc90ubLr3-2DI
content-type: application/json

### DISLIKE ###
POST http://localhost:3000/events/01bc2211-ef15-4ceb-8511-ed82c68d4d0f/dislike
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4YmQ3YmM2MC1jMGMyLTRiMTgtOTRiZS02ZjViMjk4NmRjNWEiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTQ2MjY2MTgsImV4cCI6MTY5NzY1MDYxOCwianRpIjoiMTQ2OTQwZDUtYjI1Ni00NDhlLTg0M2ItNGY4OTMyN2M2NTEzIn0.-XYdiQpanu4yNSmYsZ2kTbYxnkRYlfrc90ubLr3-2DI
content-type: application/json

### Add_video ###
POST http://localhost:3000/events/c99e523e-af6b-447f-a638-cdc624fc5dbd/videos/add_video
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkNjRmNDE0Yy1kNWM5LTRhYjAtOWQ0ZS01ODdjMDc3MWRhYjMiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTUyMjM2MjksImV4cCI6MTY5ODI0NzYyOSwianRpIjoiOGM3OGQxOWEtYTc3NS00M2NjLWE2NjEtZDNmYjk0ZjQ1MzEzIn0.pWWbSbviUXymPPhK3fuqqYqjVPU5vtENHheXkOR9lFw
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="video"; filename="RetratoFamiliar.mp4"
Content-Type: video/mp4

lib/endpoints/assets/RetratoFamiliar.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="recorded_at"

2022-09-12 14:35:03 -0300
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Delete_video ###
POST http://localhost:3000/events/c99e523e-af6b-447f-a638-cdc624fc5dbd/videos/delete_video/5d4535a3-ea7c-4969-9ef8-844d0b65be95
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkNjRmNDE0Yy1kNWM5LTRhYjAtOWQ0ZS01ODdjMDc3MWRhYjMiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTUyMjM2MjksImV4cCI6MTY5ODI0NzYyOSwianRpIjoiOGM3OGQxOWEtYTc3NS00M2NjLWE2NjEtZDNmYjk0ZjQ1MzEzIn0.pWWbSbviUXymPPhK3fuqqYqjVPU5vtENHheXkOR9lFw
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="video"; filename="Retrato Familiar.mp4"
Content-Type: video/mp4

lib/endpoints/assets/RetratoFamiliar.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### SHOW_VIDEOS ###
GET http://localhost:3000/events/c99e523e-af6b-447f-a638-cdc624fc5dbd/videos

### REVIEWS ###
GET http://localhost:3000/events/f5852279-73de-49da-b8a5-e31f875da009/reviews?reviewable_klass=artist
content-type: application/json
