### SHOW ###
GET http://localhost:3000/events/ef9fba6b-2d48-4bcc-915b-42a4b3f7e88d
content-type: application/json

### SEARCH ###
GET http://localhost:3000/events/search
content-type: application/json

### CREATE ###
POST http://localhost:3000/events
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="event"

{
    "name":"Digweed, Metropolitano 2023",
    "datetime": "2023-09-05 19:30:10",
    "artist_id": "73cf157a-0e70-4f35-960b-2e44c023a502",
    "producer_id": "ee1abc73-31a7-44d4-b45b-19242b09c7fc",
    "venue_id": "94209a94-03e3-4977-86c0-e7932b8b45f4",
    "description": "description"
}
------WebKitFormBoundary7MA4YWxkTrZu0gW

Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/jpg

< lib/endpoints/assets/ArtistCover.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### UPDATE ###
PUT http://localhost:3000/events/21c21362-70f4-40a7-863d-e43cc2cc4cb2
content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="event"

{
    "name":"Digweed Update"
}------WebKitFormBoundary7MA4YWxkTrZu0gW

Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/jpg

< /lib/endpoints/assets/ArtistCover.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### FOLLOW ###
POST http://localhost:3000/events/5760f2d7-60c8-456f-bf5e-7e92c7877736/follow
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxZGUzNmI5Mi1hOWVlLTQ3NGUtOTg3Ni0xN2Q4NDMzZGUwZWMiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTQzMDE5NjUsImV4cCI6MTY5NzMyNTk2NSwianRpIjoiOGVlMmRmNjAtMjgxYS00ZGZhLTg5MjYtNWI1OTU1Njc4NTMyIn0.0DR-fqgl2S_OvfL3Hk5j0LCbV-66YsmXXfBhnthmiGI
content-type: application/json

### UNFOLLOW ###
POST http://localhost:3000/events/5760f2d7-60c8-456f-bf5e-7e92c7877736/unfollow
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxZGUzNmI5Mi1hOWVlLTQ3NGUtOTg3Ni0xN2Q4NDMzZGUwZWMiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTQzMDE5NjUsImV4cCI6MTY5NzMyNTk2NSwianRpIjoiOGVlMmRmNjAtMjgxYS00ZGZhLTg5MjYtNWI1OTU1Njc4NTMyIn0.0DR-fqgl2S_OvfL3Hk5j0LCbV-66YsmXXfBhnthmiGI
content-type: application/json

### REVIEWS ###
GET http://localhost:3000/events/f5852279-73de-49da-b8a5-e31f875da009/reviews?reviewable_klass=artist
content-type: application/json