### RESOLVE ###
POST http://localhost:3000/reports/331bd01c-e736-4185-aae4-5989fc18fb07/resolve?report_action=accept
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3M2YwZTBhOS01YzFjLTQ2YmUtOGNjNC03M2IzYzQ3NjZlYWUiLCJzY3AiOiJ1c2VyIiwiYXVkIjpudWxsLCJpYXQiOjE2OTU4NTM2MzMsImV4cCI6MTY5ODg3NzYzMywianRpIjoiMmJlMThjMjUtOWYxMy00MDA2LTkxNDYtYTdjNTNmNzQ2YzllIn0.8PbHlwMua7DHHuuQv4lSjNh38hUK6wd0dYzduKB4aZ4
content-type: application/json